### ISSUE TITLE
Import from VDC function broken, doesnt recognize filters other than peaking and some times has blank BW and gain values

### ISSUE THREAD

**Issue by basileus-sys** [ThePBone/DDCToolbox#8]
When I make a new eq profile, export it as .VDC for Viper and try to reimport it on DDCToolbox to further modify the program fails to recognize everything, especially filters that are not of the peak type. (I had a picture of the missing BW and gain values but i lost it and i cant replicate the problem. the low shelf/high shelf filters are still missing though.)

I also tried making a EQ profile with just a low shelf and it does seem to output something:
![immagine](https://user-images.githubusercontent.com/52258368/123138168-05d3b000-d455-11eb-9c24-04c1e3c3d2e4.png)
But once imported into DDCToolbox it simply doesnt show anything.
![immagine](https://user-images.githubusercontent.com/52258368/123138283-23087e80-d455-11eb-814c-8a9ebfe1e826.png)

So if i were to guess the problem isnt with the export but with the import function?

**Comment by ThePBone** [comment]
This is expected behavior. Please consider saving your changes as a *.vdcprj (project file) if you need to modify the data later.

The 'classic VDC import' function is only designed to load _**classic**_ viper VDCs, containing **only peaking filters**.
(Original VDCs, like those created using the old VDC Toolbox 2.0, purely contained coefficients based on peaking filters; this is why we call them 'classic VDCs' here).

If you try to import a more advanced VDC based on other filters, the importer cannot reverse-calculate the coefficients and leaves unsupported data out.

**Comment by basileus-sys** [comment]
> 
> 
> This is expected behavior. Please consider saving your changes as a *.vdcprj (project file) if you need to modify the data later.
> 
> The 'classic VDC import' function is only designed to load _**classic**_ viper VDCs, containing **only peaking filters**.
> (Original VDCs, like those created using the old VDC Toolbox 2.0, purely contained coefficients based on peaking filters; this is why we call them 'classic VDCs' here).
> 
> If you try to import a more advanced VDC based on other filters, the importer cannot reverse-calculate the coefficients and leaves unsupported data out.

I see! so everything is working fine, its just that it cannot reverse calculate filters other than peak filters. Thanks a lot!
